"""MkDocs macros: expose the generated registry to page templates.

Counts and catalog rows come from docs/data/registry.json, which is generated by
scripts/build_registry.py from the earth2studio source — so nothing on the site
can drift from the code.
"""

import json
from pathlib import Path

REGISTRY = Path(__file__).parent / "data" / "registry.json"


def define_env(env):
    registry = json.loads(REGISTRY.read_text()) if REGISTRY.exists() else {}
    counts = registry.get("counts", {})

    env.variables["registry"] = registry
    env.variables["counts"] = counts

    @env.macro
    def n(key: str, field: str = "catalog") -> int:
        """Count for a registry section, e.g. n('prognostic') or n('data_sources')."""
        value = counts.get(key, 0)
        if isinstance(value, dict):          # per-module counts
            return value.get(field, 0)
        return value                          # scalar totals (models_total, vocabulary)

    @env.macro
    def entries(key: str, catalog_only: bool = True) -> list:
        """Registry rows for a section, catalog entries only by default."""
        rows = registry.get(key, [])
        return [r for r in rows if r.get("catalog")] if catalog_only else rows
